_target_: src.model.pinn.Conv1DPINN
n: ${dataset.n}
k: ${dataset.k}
t_domain: ${dataset.t_domain}
solver_params:
  hidden_channels: 64
  num_conv_layers: 3
  hidden_dim: 64
  kernel_size: 3
  activation: silu
  init_mode: normal
